DROP TABLE leveldetails IF EXISTS;

CREATE TABLE leveldetails (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL,
  levelname VARCHAR(20) NOT NULL,
  levelprice float,
  PRIMARY KEY(id)
);

DROP TABLE seatsavilability IF EXISTS;

CREATE TABLE seatsavailability(
	id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL,
	levelid int  NOT NULL,
	totalseats int  NOT NULL,
	availableseats int  NOT NULL,
	PRIMARY KEY(id)
);

DROP TABLE reservationdetails IF EXISTS;

CREATE TABLE reservationdetails(
	id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL,
	customeremail varchar(50)  NOT NULL,
	levelid int not null,
	seatscount int  NOT NULL,
	status varchar(10)  NOT NULL,
	PRIMARY KEY(id)
);
